name: Update RSS Feed
on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser PyRSS2Gen

    - name: Generate RSS Feed
      run: |
        python feed_aggregator.py \
          https://xxxclub.to/feed/MG.xml \
          https://www.torlock.com/adult/rss.xml \
          https://pornrips.to/feed/torrents \
          --output feed.xml

    # Option 1: Static Site Deployment
    - name: Deploy to Static Hosting
      uses: actions/upload-artifact@v4
      with:
        name: rss-feed
        path: feed.xml
        retention-days: 7

    # Option 2: Cloudflare Pages Deployment
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: rss-aggregator
        directory: .

    - name: Trigger External Webhook
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: rss-updated
        client-payload: |
          {
            "feed_url": "https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/aggregated_feed.xml"
          }

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: aggregated_feed.xml
        tag_name: rss-feed-${{ github.run_number }}

    - name: Manual Cloudflare Deploy
      run: |
       npm install -g @cloudflare/wrangler
       wrangler pages publish . \
       --project-name=rss-aggregator \
       --branch=main
